CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    surname character varying(30) COLLATE pg_catalog."default",
    name character varying(30) COLLATE pg_catalog."default",
    phone character varying(30) COLLATE pg_catalog."default",
    work text COLLATE pg_catalog."default",
    address character varying(300) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
)